apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  containers:
  - name: flask-app
    image: prajwal027/new-flask
    ports:
    - containerPort: 8008
      protocol: TCP
  restartPolicy: Always
...
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1 # Number of replicas(can be scaled)
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      # Same container spec from Pod definition
      containers:
      - name: flask-app
        image: prajwal027/new-flask  
        ports:
        - containerPort: 8008
          protocol: TCP
      restartPolicy: Always



