apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  containers:
  - name: flask-app
    image: prajwalpm27/python_flask1  # Replace with your actual image name (from Jenkinsfile)
    ports:
    - containerPort: 5000  # Flask app typically runs on port 5000
      protocol: TCP

    # Volume mount for database (if needed):

    # - name: database-volume

    #   mountPath: /app/database.db

    # resources:

    #   limits:

    #     memory: "1Gi"

    #     cpu: "1"

    #   requests:

    #     memory: "500Mi"

    #     cpu: "0.5"  # Adjust resource requests/limits as needed

  # Liveness/readiness probes (optional):

  # livenessProbe:

  #   httpGet:

  #     path: /health

  #     port: 5000

  #   initialDelaySeconds: 15

  #   periodSeconds: 20

  # readinessProbe:

  #   httpGet:

  #     path: /health

  #     port: 5000

  #   initialDelaySeconds: 30

  #   periodSeconds: 20
  restartPolicy: Always
  ---------------------------------------------------------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1  # Number of replicas (can be scaled)
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      # Same container spec from Pod definition
      containers:
      - name: flask-app
        image: python-flask  # Replace with your image name
        ports:
        - containerPort: 5000
          protocol: TCP
        # ... (volume mount, resources, probes - optional)
      restartPolicy: Always
------------------------------------------------------------------------------------------------------------------------------------------------



